name: CI

on:
  [push, pull_request]   # プッシュ／PR で起動

jobs:
  test:
    runs-on: windows-latest  # Windows Runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4    # コードをチェックアウト

      - name: Setup Python & cache Poetry deps
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      
      - name: Install Poetry
        run: pip install poetry


      - name: Install dependencies
        run: poetry install

      - name: Cache Godot binary
        uses: actions/cache@v3
        with:
          path: C:/godot
          key: ${{ runner.os }}-godot-${{ hashFiles('**/Godot_v4.2-*.zip') }}
          restore-keys: |
            ${{ runner.os }}-godot-

      - name: Setup Godot (headless + templates)
        uses: chickensoft-games/setup-godot@v2.2.0
        with:
          version: '4.2.0'
          export-templates: true

      - name: Run pytest
        run: poetry run pytest

      - name: Run 100-year headless simulation
        run: |
          ${{ env.GODOT }} \
            --headless \
            -s res://tests/run_100yrs.gd
